#!/usr/bin/env python
# -*- coding: utf-8 -*-

from mlproject.distance import haversine
import argparse
from termcolor import colored

description = 'Calculate the distance between two coordinates'
parser = argparse.ArgumentParser(description=description)
parser.add_argument('--coords',
                    nargs='+',
                    help='pass the 4 coordinates',
                    required=True)
# parser.add_argument('--prod',
#                     action='store_true',
#                     default=False,
#                     help='Example here')
args = parser.parse_args()
lon1, lat1, lon2, lat2 = args.coords
dist = haversine(float(lon1), float(lat1), float(lon2), float(lat2))
print(colored("###### Distance ######", "blue"))
print(colored(dist, "red"))


